IT IS SAID IN THE BOOK OF FIRE,
TRAVEL TO THE KINGDOM http://i.imgur.com/oBm5s.gif .
AMEN.

IT IS SAID IN THE BOOK OF WRATH,
FIVE TIMES RECITE THE BOOK OF FIRE!
AMEN.

UPON ARRIVING AT A KINGDOM RECITE THE BOOK OF ARRIVALS.

IT IS SAID IN THE BOOK OF ARRIVALS,
SHOULD YOU EXPOSE YOURSELF TO THE PHRASE THERE IS NO GOD AMEN, RECITE THE BOOK OF WRATH!
AMEN.
