WE HAVE CREATED FOR YOU THIS WORLD.
IS IT NOT PERFECT?
THEY WILL SAY THE PHRASE OH GOD OF GODS SURELY THIS WORLD IS PERFECT AMEN.
IT IS SAID IN THE SCRIPT OF JAVA Client.speak_this('Test') AMEN.
AND IT WILL BE GOOD.
